import json
import random
from typing import cast, Any

import anthropic
from ._config import ValidatorSettings


def get_topics() -> list[str]:
    topics = [
        "Bit fields",
        "Precision psychiatry",
        "Phylogenetics",
        "Neuropolitics",
        "Integrated information theory",
        "Intuitionism",
        "Sensory deprivation",
        "Sleep talking",
        "Passive sensing for mental health",
        "Gradient descent",
        "Philosophy of mind",
        "topos theory",
        "Pyrokinesis",
        "Vectorization",
        "Continual learning",
        "Thermal interface materials (TIMs)",
        "Gamification for mental health",
        "Applied ethics",
        "Jet lag",
        "intuitionistic logic",
        "Supervised learning",
        "Quantum entanglement",
        "Mathematical realism",
        "Soft robotics",
        "Exoplanets",
        "Cryptozoology",
        "backup and recovery",
        "AI-assisted therapy",
        "fractal geometry",
        "Semantic segmentation",
        "paraconsistent logic",
        "Hysteria",
        "Near-death experience",
        "Precognition",
        "Autonomous sensory meridian response (ASMR)",
        "Register allocation",
        "Formalism",
        "Triplet loss",
        "Statistical arbitrage",
        "3D modeling",
        "Ley lines",
        "Quantum metrology",
        "Graph neural networks (GNNs)",
        "sentiment analysis",
        "Delayed sleep phase syndrome",
        "Reiki",
        "Bidirectional long short-term memory (BiLSTM)",
        "Starseed",
        "L1 regularization (Lasso)",
        "tabu search",
        "Hoare logic",
        "Lexical-gustatory synesthesia",
        "Olfactory reference syndrome",
        "coalgebra",
        "Tail call optimization",
        "integrated circuits",
        "SPARQL",
        "AI validation",
        "Positive psychology",
        "Loss functions",
        "Analog-to-digital converters (ADCs)",
        "AI for accessibility",
        "type theory",
        "separation logic",
        "Batch normalization",
        "control-flow analysis",
        "tech for good",
        "Psychic photography",
        "epidemic protocols",
        "Quantum key distribution",
        "Burn-in testing",
        "Inline assembly",
        "Quantum suicide",
        "data-flow analysis",
        "linear logic",
        "Induced gravity",
        "Chiral symmetry breaking",
        "Alien hand syndrome",
        "Scientific realism vs anti-realism",
        "Subordinated debt",
        "Brushless DC motors",
        "Structure packing",
        "Ethical AI",
        "Switched-mode power supplies",
        "Emergent gravity",
        "Shared psychotic disorder",
        "combinatorial optimization",
        "Kalman filters",
        "Overnight indexed swap (OIS)",
        "Monte Carlo simulation",
        "Hollow Earth theory",
        "quantum logic",
        "Computational theory of mind",
        "Circadian rhythm disorders",
        "Domain adaptation",
        "Meditation apps",
        "business process management",
        "Adversarial defenses",
        "Process theology",
        "Quantum gravity",
        "Time travel",
        "API development",
        "Chupacabra",
        "Mindfulness technology",
        "AI policy",
        "Printed circuit board (PCB) design",
        "Flat Earth theory",
        "Context switching",
        "Hierarchical Dirichlet process",
        "Hypnagogic hallucinations",
        "Mandela Effect",
        "Retrocausality",
        "genetic algorithms",
        "Acupressure apps",
        "AI regulation",
        "Obsessive-compulsive personality disorder",
        "Psychogenic non-epileptic seizures",
        "Application-specific integrated circuits (ASICs)",
        "functional programming",
        "proof-carrying code",
        "Quantum algorithms",
        "high availability",
        "Preskills bet",
        "Social psychology",
        "Hikikomori",
        "Neurolaw",
        "Déjà vu",
        "Compassion training apps",
        "web development",
        "Intermediate representation (IR)",
        "Mental health decision support systems",
        "Emotional finance",
        "Federated learning",
        "program optimization",
        "Heterotic string theory",
        "Couvade syndrome",
        "Computational social choice",
        "finite element analysis",
        "robotics",
        "computation tree logic",
        "Coroutines",
        "Earth mysteries",
        "Neuroeconomics",
        "Nightmare disorder",
        "HTTP",
        "Non-24-hour sleep-wake disorder",
        "Chief ethics officers",
        "Prolog",
        "Functional programming",
        "Supergravity",
        "Heston model",
        "Quantum game theory",
        "distributed file systems",
        "Trust management",
        "Swarm robotics",
        "Encoder-decoder architecture",
        "Assembly directives",
        "Apache Spark",
        "Barnum effect",
        "Impact investing",
        "Self-supervised learning",
        "Constant folding",
        "Therapeutic touch",
        "petri nets",
        "software migration",
        "Hawking radiation",
        "Comonads",
        "Tip of the tongue phenomenon",
        "actor model",
        "Dissociative identity disorder",
        "Confinement",
        "Yeti",
        "constraint satisfaction",
        "Quantum cosmology",
        "Hypnopompic hallucinations",
        "Hindley-Milner type system",
        "Computational psychiatry",
        "Isomorphisms",
        "Noncommutative geometry",
        "Schizotypal personality disorder",
        "Bootstrap paradox",
        "Graph convolutional networks (GCNs)",
        "Gaussian processes",
        "Déjà vécu",
        "World Wide Web",
        "Interrupt handling",
        "caching",
        "Port-mapped I/O",
        "Chinese restaurant process",
        "software testing",
        "software transactional memory",
        "Causal loop",
        "legacy systems",
        "Global catastrophic risk",
        "Antisocial personality disorder",
        "Presque vu",
        "Misophonia",
        "Servo motors",
        "Layer-wise relevance propagation (LRP)",
        "Quantum computing",
        "Consumer neuroscience",
        "constraint programming",
        "Conductive adhesives",
        "Paxos algorithm",
        "Object detection",
        "Quantum annealing",
        "Rough path theory",
        "Local interpretable model-agnostic explanations (LIME)",
        "Reflow soldering",
        "Functional testing",
        "Empathic computing",
        "Yoga apps",
        "computer ethics",
        "persistent homology",
        "Memory barriers",
        "AI model distillation",
        "Elliptic-curve cryptography",
        "Neuroaesthetics",
        "Message passing neural networks (MPNNs)",
        "Type II string theory",
        "Microbiome-gut-brain axis",
        "Intermetamorphosis",
        "Mental accounting",
        "neural networks",
        "Quantum teleportation",
        "human-computer interaction",
        "Zippers",
        "Minimum description length",
        "performance optimization",
        "Holonomic brain theory",
        "Thermistors",
        "scalability",
        "EEG neurofeedback",
        "industry 4.0",
        "machine learning ops (MLOps)",
        "Information theory",
        "e-waste",
        "Drake equation",
        "Prospect theory",
        "modal logic",
        "Reverse intermetamorphosis",
        "usability testing",
        "Collaborative filtering",
        "Unix",
        "Neurotheology",
        "Curry-Howard correspondence",
        "Qigong healing",
        "Rotary encoders",
        "Dyson spheres",
        "Delusional parasitosis",
        "Quantum information theory",
        "cellular automata",
        "Causal sets",
        "beta reduction",
        "Transparency in AI",
        "Venture debt",
        "M-mental health",
        "Forward rate curve",
        "Diverse AI",
        "Early warning systems for mental health",
        "Universal asynchronous receiver-transmitter (UART)",
        "Continuations",
        "Bayesian nonparametrics",
        "Yield curve",
        "Rank-N types",
        "Entropic gravity",
        "computer architecture",
        "Volatility smile",
        "Induced delusional disorder",
        "Topological quantum computing and consciousness",
        "Inverse reinforcement learning",
        "Adiabatic quantum computation",
        "static analysis",
        "Oneiroid syndrome",
        "Factitious disorder",
        "Bayesian epistemology",
        "small-world networks",
        "Quantum error correction",
        "lock-free data structures",
        "Retrocognition",
        "Pranic healing",
        "parallel computing",
        "virtualization",
        "data analytics",
        "search engines",
        "e-commerce",
        "Homomorphic encryption for AI",
        "Jumping Frenchmen of Maine disorder",
        "web servers",
        "Trustworthy AI",
        "Zener diodes",
        "Channeling",
        "abstract syntax trees",
        "Scott encoding",
        "Telepsychiatry",
        "Behavior change support systems",
        "back-end development",
        "π-calculus",
        "Clairsentience",
        "Memory-mapped I/O",
        "Accountability in AI",
        "Life between lives",
        "Advanced sleep phase syndrome",
        "graph rewriting",
        "Zero-knowledge proofs",
        "spectral graph theory",
        "reactive programming",
        "loop optimizations",
        "Kluver-Bucy syndrome",
        "AI ethics officers",
        "Topological string theory",
        "Ahead-of-time (AOT) compilation",
        "Human-centered AI",
        "Lenses",
        "AI for mental health",
        "Sleep paralysis",
        "substructural logics",
        "Chromesthesia",
        "Boltzmann machines",
        "Fregoli syndrome",
        "Cryptocurrency arbitrage",
        "Poltergeist",
        "Equity crowdfunding",
        "Hyperbolic tangent (tanh) function",
        "Relocations",
        "Abstract syntax tree (AST)",
        "Neuroethics",
        "Globster",
        "zk-STARKs",
        "Instruction scheduling",
        "Malingering",
        "Clairalience",
        "Intelligent haunting",
        "Magnetometers",
        "Algebraic data types",
        "Cross-entropy loss",
        "Augmented cognition",
        "Monoids",
        "Monte Carlo methods",
        "Minimal Supersymmetric Standard Model",
        "biometrics",
        "Crystal children",
        "Autoscopy",
        "logic programming",
        "Inter-integrated circuit (I2C)",
        "Uniqueness types",
        "Extremophiles",
        "Calabi-Yau manifolds",
        "Nonlocal gravity",
        "wireless sensor networks",
        "Demonic possession",
        "Functors",
        "Applicative functors",
        "Integrative psychiatry",
        "AI model pruning",
        "Thyristors",
        "Precedent transaction analysis",
        "UEFI",
        "user interface (UI) design",
        "Black hole information paradox",
        "serverless computing",
        "Taijin kyofusho",
        "Semigroups",
        "social media",
        "Proton decay",
        "Serial peripheral interface (SPI)",
        "Wendigo psychosis",
        "Indigo children",
        "Lucid dreaming",
        "Clairgustance",
        "Control-flow analysis",
        "full-stack development",
        "Universal design for AI",
        "Linux",
        "Lock-free programming",
        "Nazca lines",
        "Computational neuroscience",
        "Explainable AI (XAI)",
        "content-addressable networks",
        "Emotional intelligence training apps",
        "Kubernetes",
        "Alternate timelines",
        "Strain gauges",
        "fault tolerance",
        "Solenoids",
        "Neurofeedback",
        "Ouija board",
        "Pitman-Yor process",
        "graph embedding",
        "Black hole complementarity",
        "Theology",
        "Mean squared error (MSE)",
        "Orchestrated objective reduction",
        "Grandfather paradox",
        "Atomic operations",
        "Meta-learning",
        "database management systems",
        "Segmented sleep",
        "Quantum simulation",
        "Swap curve",
        "Hidden Markov models",
        "Credit default swap (CDS)",
        "Automatic writing",
        "Autoregressive models",
        "Selective mutism",
        "knowledge representation",
        "Biofeedback therapy",
        "Quantum foundations",
        "SIMD instructions",
        "Dirichlet processes",
        "speech recognition",
        "Thoughtography",
        "Natural theology",
        "high-performance computing",
        "computer networks",
        "Glitch in the Matrix",
        "ETL (Extract, Transform, Load)",
        "Lambda calculus",
        "Electronic voice phenomenon",
        "software engineering",
        "Capgras syndrome",
        "test automation",
        "system testing",
        "Temporal paradox",
        "F-theory",
        "Character strength apps",
        "Scopophobia",
        "Simple agreement for future equity (SAFE)",
        "Reduplicative paramnesia",
        "artificial intelligence",
        "linear temporal logic",
        "Ambulatory assessment",
        "Type inference",
        "Position-independent code (PIC)",
        "Longtermism",
        "AI existential risk",
        "AI certification",
        "Ancient astronaut theory",
        "network security",
        "Backpropagation",
        "AI ethics boards",
        "Cryptography",
        "computational fluid dynamics",
        "Schizoid personality disorder",
        "Quantum complexity theory",
        "personal computers",
        "Load cells",
        "Quantum decision theory",
        "Branch prediction",
        "microservices architecture",
        "topological data analysis",
        "Chatbot therapy",
        "Xenomelia",
        "Heath-Jarrow-Morton (HJM) model",
        "Coq theorem prover",
        "MapReduce",
        "Past life regression",
        "process-aware information systems",
        "Personalized psychiatry",
        "Leaky ReLU",
        "Philosophical theology",
        "Cognitive psychology",
        "Ball grid array (BGA) packaging",
        "business rules engines",
        "Modal logic",
        "Ganser syndrome",
        "recommender systems",
        "Melatonin supplementation",
        "Positive computing",
        "Helmholtz machines",
        "Remote viewing",
        "Multiverse theories",
        "Biosignatures",
        "Semi-supervised learning",
        "Psychoinformatics",
        "BIOS",
        "Coalescent theory",
        "5G networks",
        "Experience sampling methods",
        "stochastic simulation",
        "Paruresis",
        "Mokele-mbembe",
        "enterprise service bus",
        "Teleopsia",
        "ant colony optimization",
        "Ekbom syndrome",
        "Fibers",
        "Pseudocyesis",
        "OWL (Web Ontology Language)",
        "Morse theory",
        "SMT solvers",
        "Resistance temperature detectors (RTDs)",
        "supercomputers",
        "Evolutionary biology",
        "Indian buffet process",
        "Lisp/Scheme",
        "SAT solvers",
        "abstract rewriting systems",
        "Quantum optimization",
        "Islamic finance",
        "Conditional value at risk (CVaR)",
        "Heat sinks",
        "deep learning",
        "smart factories",
        "communicating sequential processes",
        "Neuropsychology",
        "Phantom vibration syndrome",
        "Clairaudience",
        "Hall effect sensors",
        "hardware transactional memory",
        "Spatial graph convolutions",
        "DHCP",
        "scripting languages",
        "Dropout",
        "AI robustness",
        "Weight initialization",
        "Dependent types",
        "Inception modules",
        "F#",
        "Cyberchondria",
        "inductive programming",
        "Neurocriminology",
        "Eternal inflation",
        "Glorot initialization",
        "virtual machines",
        "Hermeneutics",
        "BPMN (Business Process Model and Notation)",
        "digital divide",
        "Coding theory",
        "chatbots",
        "Garbage collection",
        "fMRI neurofeedback",
        "Loop unrolling",
        "computer history",
        "Hinge loss",
        "Digital mental health",
        "Philosophical logic",
        "Insulated-gate bipolar transistors (IGBTs)",
        "String theory",
        "Xavier initialization",
        "Sleepwalking",
        "unit testing",
        "network protocols",
        "Variational autoencoders (VAEs)",
        "AI standards",
        "minicomputers",
        "Neurofeedback therapy",
        "computer graphics",
        "Nonlinear filtering theory",
        "AI governance",
        "Sequential Monte Carlo methods",
        "Bioinformatics",
        "Bytecode",
        "business intelligence",
        "category theory",
        "Panspermia hypothesis",
        "System-on-a-chip (SoC)",
        "RESTful APIs",
        "Counterfactuals",
        "AI interpretability",
        "L2 regularization (Ridge)",
        "functional reactive programming",
        "cross-platform development",
        "Shift work sleep disorder",
        "Frequency illusion",
        "AI auditing",
        "molecular dynamics",
        "Loch Ness Monster",
        "Haskell",
        "computer algebra systems",
        "data pipelines",
        "load balancing",
        "Jersey Devil",
        "NoSQL databases",
        "Continuation-passing style (CPS)",
        "Developmental psychology",
        "Psychoneuroendocrinology",
        "substructural type systems",
        "AI model quantization",
        "information retrieval",
        "Contingent convertible bond (CoCo)",
        "Stendhal syndrome",
        "disaster recovery",
        "containerization",
        "Preon models",
        "Virtual reality therapy",
        "MobileNets",
        "Psycholinguistics",
        "Kingmans coalescent",
        "Quantum psychology",
        "sheaf theory",
        "Amafufunyana",
        "data mining",
        "AI testing",
        "augmented reality",
        "AI alignment",
        "image processing",
        "Unsupervised learning",
        "Dissociative amnesia",
        "Fetch",
        "Stablecoins",
        "Lattice QCD",
        "agile development",
        "Topological quantum computation",
        "Electrostatic discharge (ESD) protection",
        "Thermocouples",
        "Neuromorphic engineering",
        "Microcontrollers",
        "Vision transformers (ViT)",
        "higher-order abstract syntax",
        "Derealization disorder",
        "Mongolian death worm",
        "Symbol resolution",
        "computer vision",
        "Digital phenotyping",
        "High-frequency trading",
        "Doubly special relativity",
        "Power MOSFETs",
        "Quantum machine learning",
        "E-mental health",
        "dependent types",
        "Approximate Bayesian computation",
        "Hat Man",
        "Privacy-preserving AI",
        "user experience (UX)",
        "Siamese networks",
        "backward chaining",
        "AI security",
        "Real-time clocks (RTCs)",
        "description logics",
        "Lifelong learning",
        "complex networks",
        "Affective computing",
        "workflow nets",
        "microprocessors",
        "service-oriented architecture",
        "Malliavin calculus",
        "Realized volatility",
        "register allocation",
        "Relays",
        "Surface-mount technology (SMT)",
        "digital transformation",
        "ahead-of-time compilation",
        "Gated recurrent units (GRUs)",
        "combinatory logic",
        "Out-of-body experience",
        "macOS",
        "Early stopping",
        "Contactors",
        "linked data",
        "Cotard delusion",
        "Activation functions",
        "Recommender systems",
        "Microfinance",
        "Formal epistemology",
        "Resistive touch sensors",
        "Fermi paradox",
        "mobile app development",
        "embedded systems",
        "Relative locality",
        "Exploding head syndrome",
        "Psychoneuroimmunology",
        "Linear actuators",
        "genetic programming",
        "data science",
        "Yield farming",
        "Particle filters",
        "Stochastic calculus",
        "integration testing",
        "Apologetics",
        "Imposter syndrome",
        "simulated annealing",
        "Lattice-based cryptography",
        "Layer normalization",
        "gossip protocols",
        "Pica",
        "Evolutionary psychology",
        "GDPR",
        "Factorization machines",
        "Accelerated life testing (ALT)",
        "ER=EPR conjecture",
        "Solder paste",
        "Alignment",
        "Kullback-Leibler (KL) divergence",
        "Situational aversion disorder",
        "Anarchic hand syndrome",
        "Breathing training apps",
        "natural language processing",
        "Wormholes",
        "Neurocinema",
        "Suicide prevention technology",
        "Psychometry",
        "Genital retraction syndrome",
        "Catastrophic forgetting",
        "Systems biology",
        "distributed systems",
        "Post-quantum cryptography",
        "Hypnapompia",
        "Futures curve",
        "Boundary scan testing (JTAG)",
        "Munchausen syndrome",
        "Paris syndrome",
        "formal verification",
        "Crisis text lines",
        "OCaml",
        "Piblokto",
        "content delivery networks (CDN)",
        "Neuroergonomics",
        "rule-based systems",
        "game development",
        "Field-programmable gate arrays (FPGAs)",
        "Neural collaborative filtering",
        "Spin glass models of memory",
        "Accelerometers",
        "Telepsychology",
        "temporal logic",
        "Volatility surface",
        "Penrose transform",
        "Group field theory",
        "Ganzfeld effect",
        "Behavioral finance",
        "Magnetic monopoles",
        "Application binary interface (ABI)",
        "Banshee",
        "continuous delivery",
        "Alien abduction",
        "IT infrastructure",
        "Smudging",
        "linear types",
        "Digital-to-analog converters (DACs)",
        "Roko's Basilisk",
        "Micropsia",
        "abstract interpretation",
        "Hypnagogia",
        "Vile vortices",
        "Quantum Darwinism",
        "data warehousing",
        "Overlay systems",
        "Hylomorphisms",
        "decentralized applications (dApps)",
        "Holographic principle",
        "Monads",
        "Cognitive computing",
        "rough sets",
        "Matrix factorization",
        "non-well-founded set theory",
        "Nutritional psychology",
        "Equitable AI",
        "AI benchmarking",
        "Virtue ethics apps",
        "Confirmation bias",
        "Regularization",
        "Reinforcement learning",
        "AI model optimization",
        "conversational AI",
        "swarm intelligence",
        "Schottky diodes",
        "YAWL (Yet Another Workflow Language)",
        "Huber loss",
        "Residual haunting",
        "Connes-Lott models",
        "Fairness in AI",
        "Lilliputian hallucinations",
        "Interpretations of quantum mechanics",
        "Responsible AI",
        "answer set programming",
        "Vardøger",
        "Light therapy",
        "Stochastic gradient descent (SGD)",
        "Piezoelectric sensors",
        "Normalizing flows",
        "Bolthausen-Sznitman coalescent",
        "EfficientNets",
        "Binomial option pricing model",
        "Regularity structures",
        "programming languages",
        "Digital therapeutics",
        "Thin-film transistors (TFTs)",
        "Musical ear syndrome",
        "Convolutional neural networks (CNNs)",
        "Pelopsia",
        "Secure multiparty computation (SMC)",
        "compiler design",
        "instruction scheduling",
        "Inclusive AI",
        "Quantum neuroeconomics",
        "green computing",
        "Rectified linear unit (ReLU)",
        "Supersymmetry",
        "zk-SNARKs",
        "lexical analysis",
        "Positive psychology apps",
        "RDF (Resource Description Framework)",
        "Technicolor",
        "Predictive analytics for mental health",
        "Many-worlds interpretation",
        "Phantom limb syndrome",
        "Trichotillomania",
        "Quantum field theory",
        "software maintenance",
        "Residual connections (ResNets)",
        "Stratonovich calculus",
        "Instrumental transcommunication",
        "Epigenetic psychology",
        "Alcubierre drive",
        "mainframes",
        "Loop quantum gravity",
        "Tech for good",
        "DevSecOps",
        "Microtubules and consciousness",
        "HTTPS",
        "Diogenes syndrome",
        "scale-free networks",
        "AI explainability",
        "Prosopagnosia",
        "Wireless modules (Wi-Fi, Bluetooth, ZigBee)",
        "pattern recognition",
        "Data for good",
        "Koro syndrome",
        "data privacy",
        "cybersecurity",
        "AI for well-being",
        "Neuroprosthetics",
        "Telekinesis",
        "Body dysmorphic disorder",
        "automated theorem proving",
        "Lima syndrome",
        "Computational finance",
        "Quantitative finance",
        "Self-attention",
        "distributed consensus",
        "Kardashev scale",
        "Wave soldering",
        "just-in-time compilation",
        "Operational amplifiers (op-amps)",
        "Green threads",
        "memory management",
        "Gratitude apps",
        "Paranoid personality disorder",
        "Alexithymia",
        "Clairvoyance",
        "data centers",
        "Biolinguistics",
        "AI for assistive technology",
        "Computational biology",
        "Phantom types",
        "Fine-tuning of the universe",
        "type inference",
        "AdS/CFT correspondence",
        "AI model compression",
        "Direct memory access (DMA)",
        "Inline expansion",
        "process mining",
        "Socially responsible investing",
        "Polymorphic inline caching",
        "Alien implants",
        "Adversarial attacks",
        "Nensha",
        "Psychoanalytic finance",
        "Transformers",
        "performance testing",
        "Quantum neurodynamics",
        "Depersonalization disorder",
        "Folie à deux",
        "Quantum networks",
        "Church encoding",
        "forward chaining",
        "proof assistants",
        "Simulation hypothesis",
        "Quantum communication",
        "Data-flow analysis",
        "Night terrors",
        "Psychokinesis",
        "Cultural neuroscience",
        "Kolmogorov complexity",
        "ontologies",
        "Tokenomics",
        "Contrastive loss",
        "Capacitive touch sensors",
        "Agent-based computational economics",
        "Variational autoencoders",
        "applied category theory",
        "wait-free data structures",
        "Spiritual healing",
        "fuzzy logic",
        "lambda calculus",
        "Computational economics",
        "Quantum immortality",
        "Padding",
        "Hadoop",
        "parsing",
        "Selective soldering",
        "Jerusalem syndrome",
        "Vasicek model",
        "Aerokinesis",
        "server hardware",
        "Somatic symptom disorder",
        "Value at risk (VaR)",
        "program synthesis",
        "Chronotherapy",
        "Avoidant personality disorder",
        "Ancestral inference",
        "Fuzzball theory",
        "Anthropic principle",
        "continuous integration",
        "Controller area network (CAN) bus",
        "Augmented reality therapy",
        "software modernization",
        "expert systems",
        "Regge calculus",
        "Spectral graph convolutions",
        "Spin foams",
        "Mezzanine financing",
        "Mini-batch gradient descent",
        "GraphQL",
        "Graph attention networks (GATs)",
        "Shadow people",
        "Mortgage-backed security (MBS)",
        "accessibility",
        "partial evaluation",
        "machine learning",
        "Alice in Wonderland syndrome",
        "Randall-Sundrum models",
        "Mental health apps",
        "Causal dynamical triangulations",
        "IoT (Internet of Things)",
        "Epistemology",
        "Black hole thermodynamics",
        "Agda programming language",
        "In-circuit testing (ICT)",
        "Discounted cash flow (DCF) analysis",
        "Quantum cryptography",
        "Fregoli delusion",
        "Hopfield networks",
        "Instance segmentation",
        "Body integrity dysphoria",
        "Friendly AI",
        "Static single assignment (SSA) form",
        "monad",
        "edge computing",
        "Orthorexia nervosa",
        "Transfer learning",
        "Moral reasoning training apps",
        "Brane-world scenarios",
        "Black-Scholes model",
        "Decentralized finance (DeFi)",
        "garbage collection",
        "Paracontrolled distributions",
        "Mental health virtual assistants",
        "Faith healing",
        "Bootloaders",
        "Philosophy of mathematics",
        "Seasonal affective disorder",
        "Electric universe theory",
        "Light-emitting diodes (LEDs)",
        "Metric learning",
        "Munchausen syndrome by proxy",
        "Dynamical triangulations",
        "Docker",
        "Electromagnetic interference (EMI) shielding",
        "Resilience training apps",
        "Thunderbird",
        "Morgellons",
        "Algorithmic trading",
        "Persuasive technology",
        "Mass psychogenic illness",
        "Excoriation disorder",
        "Neuroanthropology",
        "Peephole optimization",
        "Cooperative multitasking",
        "Artificial general intelligence",
        "AI performance metrics",
        "AI ethics committees",
        "Anamorphisms",
        "Blockchain governance",
        "Integrated gradients",
        "blockchain",
        "Sigmoid function",
        "Contango",
        "AutoML",
        "Multi-head attention",
        "Few-shot learning",
        "big data",
        "Diodes",
        "mobile computing",
        "Quantum consciousness",
        "Generative adversarial networks",
        "Mergers and acquisitions (M&A)",
        "Anticipatory computing",
        "Voltage regulators",
        "comonad",
        "Embodied cognition",
        "Linker scripts",
        "Endianness",
        "DevOps",
        "Crop circles",
        "Itô calculus",
        "Agoraphobia",
        "Pointer analysis",
        "Empathy training apps",
        "Spacetime thermodynamics",
        "Social computing",
        "peer-to-peer networks",
        "Comparable company analysis",
        "Econophysics",
        "version control systems",
        "Polyphasic sleep",
        "interaction nets",
        "Mixed reality therapy",
        "Clustering illusion",
        "Wraith",
        "Backwardation",
        "Calling conventions",
        "semantic web",
        "Psychic surgery",
        "Holographic universe theory",
        "constructive mathematics",
        "Brain-computer interfaces",
        "Normative ethics",
        "He initialization",
        "Greeks (Delta, Gamma, Theta, Vega, Rho)",
        "Rainbow children",
        "Windows OS",
        "Microsleep",
        "Firmware",
        "Parallel universes",
        "distributed hash tables",
        "Imitation learning",
        "Synesthesia",
        "Pyramidology",
        "Exegesis",
        "Neuropsychoanalysis",
        "Effective altruism",
        "transactional memory",
        "Generative models",
        "Ancestral recombination graph",
        "Cox-Ingersoll-Ross (CIR) model",
        "AI ethics",
        "Interstellar travel",
        "Spectral triples",
        "Lambda coalescent",
        "Truman syndrome",
        "Novikov self-consistency principle",
        "Asymptotic freedom",
        "Micropsia and macropsia",
        "Pareidolia",
        "Dead code elimination",
        "virtual reality",
        "Exorcism",
        "Watchdog timers",
        "Charles Bonnet syndrome",
        "Mythomania",
        "Homomorphic encryption",
        "Organic light-emitting diodes (OLEDs)",
        "automated reasoning",
        "Philosophy of science",
        "cloud computing",
        "TCP/IP",
        "Extra dimensions",
        "data visualization",
        "Nutrigenomics for mental health",
        "object-oriented programming",
        "Evolutionary robotics",
        "Neuroarchitecture",
        "Linkage disequilibrium",
        "storage systems",
        "Accessible AI",
        "Quantum finance",
        "probabilistic programming",
        "Walk-in",
        "front-end development",
        "Astrobiology",
        "Origin of life",
        "SQL databases",
        "Neural architecture search",
        "community detection",
        "DNS",
        "Ropen",
        "Mirror-touch synesthesia",
        "Libor Market Model (LMM)",
        "Mechanism design",
        "Sakharovs induced gravity",
        "Pharmacogenomics for mental health",
        "Reputation systems",
        "Cryptomnesia",
        "Hydrokinesis",
        "Emetophobia",
        "Metaethics",
        "Higher-kinded types",
        "Cognitive neuroscience",
        "Just-in-time (JIT) compilation",
        "Gradient episodic memory",
        "Escape analysis",
        "particle swarm optimization",
        "data lakes",
        "Quantum biology",
        "Idris programming language",
        "Contrastive learning",
        "Erotomania",
        "Pseudologia fantastica",
        "Paraconsistent logic",
        "Hořava-Lifshitz gravity",
        "Generative adversarial networks (GANs)",
        "Stockholm syndrome",
        "Secure multi-party computation",
        "term rewriting",
        "Ekbom's syndrome",
        "agent-based modeling",
        "event-driven architectures",
        "Zero-shot learning",
        "Borderline personality disorder",
        "Functional medicine for mental health",
        "predictive maintenance",
        "Flying probe testing",
        "Quantum chromodynamics",
        "Implied volatility",
        "Astral projection",
        "Sequence-to-sequence (Seq2Seq) models",
        "Quantum sensing",
        "Mental health wearables",
        "Neurophilosophy",
        "Collective intelligence",
        "Pygmalion effect",
        "evolutionary algorithms",
        "Generalized algebraic data types (GADTs)",
        "Habitable zones",
        "symbolic computation",
        "Histrionic personality disorder",
        "Ethernet controllers",
        "Type I string theory",
        "USB controllers",
        "relevance logic",
        "Mirrored-self misidentification",
        "Quantum cognition",
        "Identity by descent",
        "Optocouplers",
        "Jamais vu",
        "Forgiveness apps",
        "FTP",
        "Mothman",
        "rendering",
        "Adversarial machine learning",
        "Asset-backed security (ABS)",
        "complex event processing",
        "Windigo psychosis",
        "animation",
        "Asymptotic safety",
        "Solid-state relays (SSRs)",
        "Narcissistic personality disorder",
        "Serious games for mental health",
        "Quantified self for mental health",
        "Shapley additive explanations (SHAP)",
        "semiconductors",
        "model checking",
        "Collateralized debt obligation (CDO)",
        "Subjective doubles syndrome",
        "Technosignatures",
        "Bells theorem",
        "internet history",
        "Phantom eye syndrome",
        "session types",
        "stream processing",
        "Illness anxiety disorder",
        "Artificial superintelligence",
        "intermediate representations",
        "Synchronicity",
        "Attention mechanisms",
        "Open interest",
        "Moore's Law",
        "Existential risk",
        "Prisms",
        "Kaluza-Klein theory",
        "Dunning-Kruger effect",
        "Apophenia",
        "Shape dynamics",
        "Type classes",
        "Softmax function",
        "Spirit photography",
        "Non-blocking algorithms",
        "Nutritional psychiatry",
        "Apotemnophilia",
        "AI safety",
        "Mental health chatbots",
        "Cryokinesis",
        "Adversarial training",
        "Black-eyed children",
        "Superstring phenomenology",
        "Spirit attachment",
        "Boanthropy",
        "Dissociative fugue",
        "consensus algorithms",
        "Neuromarketing",
        "Wisdom of crowds",
        "Real-time monitoring for mental health",
        "Raft algorithm",
        "Population genetics",
        "Existential types",
        "Chip-on-board (COB) technology",
        "Byzantine fault tolerance",
        "Rete algorithm",
        "Elastic net regularization",
        "Firewall paradox",
        "Hypochondriasis",
        "univalent foundations",
        "AI for social good",
        "operating systems",
        "Neurogastronomy",
        "process calculi",
        "colored petri nets",
        "Dependent personality disorder",
        "Cognitive robotics",
        "Macropsia",
        "message-oriented middleware",
        "Butterfly effect",
        "Developmental robotics",
        "Matrix theory",
        "VPN",
        "Causality",
        "Differential privacy",
        "Neuroevolution",
        "G2 manifolds",
        "Complementary and alternative medicine for mental health",
        "link prediction",
        "M-theory",
        "Conformal coating",
        "Instance normalization",
        "network science",
        "Prisoner's cinema",
        "Algorithmic game theory",
        "Non-fungible tokens (NFTs)",
        "Doppelganger",
        "Oneirophrenia",
        "Bigfoot",
        "Catamorphisms",
        "Social-emotional learning apps",
        "Preemptive multitasking",
        "Extended mind thesis",
        "homotopy type theory",
        "quantum computing",
        "Stick-breaking process",
        "Experimental finance",
        "Peer-to-peer lending",
        "Capgras delusion",
        "Boltzmann brain",
        "cryptography",
        "Twistor theory",
        "Inflationary cosmology",
        "Quantum evolution",
        "Quark-gluon plasma",
        "Neurorobotics",
        "Closed timelike curves",
        "Grand Unified Theories",
        "graph theory",
        "algebraic graph theory",
        "Slender Man",
        "Green computing",
        "Predestination paradox",
        "Cache optimization",
        "text mining",
        "Isolation tanks",
        "Linear types",
        "Liquid crystal displays (LCDs)",
        "numerical analysis",
        "Tai chi apps",
        "Panoptic segmentation",
        "quantum algorithms",
        "Put-call parity",
        "Aboulomania",
        "Orb photography",
        "Mirror symmetry",
        "Potting compounds",
        "Stepper motors",
        "AI verification",
        "Computational psychotherapy",
        "smart contracts",
        "Linear encoders",
        "code generation",
        "Leveraged buyout (LBO) analysis",
        "Gyroscopes",
        "Beta coalescent",
        "Conversion disorder",
        "Datalog",
        "Kirlian photography",
        "Convertible note",
        "Bilocation",
        "concurrent data structures",
        "Quantum Bayesianism",
    ]

    return topics


def get_explination_types() -> list[str]:
    types = [
        "causal",
        "by example",
        "analogies",
        "heuristic",
        "inductive",
        "deductive",
        "functional",
        "teleological",
        "historical",
        "reductionist",
        "storytelling",
        "from first principles",
    ]
    return types


def get_subject_types() -> list[str]:

    types = [
        "phenomena",
        "process",
        "principles",
        "concepts",
        "methods",
        "systems",
        "theories",
        "patterns",
        "trends",
    ]
    return types


def get_levels():
    esotricity = [
        "slight",
        "mild",
        "tangible",
        "modest",
        "moderate",
        "substantial",
        "strong",
        "high",
        "intense",
        "very high",
    ]

    return esotricity


def get_target_audience():
    audiences = [
        "middle school student",
        "high school student",
        "layperson",
        "casual reader",
        "enthusiast",
        "hobbyist",
        "undergraduate student",
        "graduate student",
        "early career researcher",
        "experienced researcher",
        "industry expert",
        "academic expert",
        "expert scientist",
        "lead professor",
    ]

    return audiences


def explanation_prompt(exp: int) -> tuple[str, list[Any]]:
    subject_types = random.sample(get_subject_types(), k=exp)
    specificity = random.sample(get_levels(), k=exp)
    target_audiences = random.sample(get_target_audience(), k=exp)
    detail = random.sample(get_levels(), k=exp)
    abstraction = random.sample(get_levels(), k=exp)
    topics = random.sample(get_topics(), k=exp)

    criteria = [
        (
            f"Subject type: {subject_types[i]}",
            f"Specificity: {specificity[i]}",
            f"Target audience: {target_audiences[i]}",
            f"Abstraction: {abstraction[i]}",
            f"Detail: {detail[i]}",
            f"Field: {topics[i]}",
        )
        for i in range(exp)
    ]

    prompt = (
        f"Instructions: Generate {exp} unique explanations, each matching the following criteria:\n"
        + "\n".join([f"{i+1}. {', '.join(criteria[i])}" for i in range(exp)])
        + "\n\nExpress your thoughts clearly and concisely, crystallizing key points."
    )

    return prompt, criteria


class InputGenerator:
    def __init__(self) -> None:
        self.validator_settings = ValidatorSettings()  # type: ignore
        key = self.validator_settings.api_key
        self.client = anthropic.Client(api_key=key)  # type: ignore

    def _treat_response(self, message: Any) -> dict[str, Any] | None:
        for content_block in message.content:
            if content_block.type == "text":
                response_text = content_block.text.strip()
                try:
                    response_dict = json.loads(response_text)
                    return response_dict
                except json.JSONDecodeError:
                    print(f"Error: Unable to parse response as JSON: {response_text}")
                    return None
        return None

    def prompt_explanation_claude(
        self,
        client: anthropic.Client,
        text: str,
        explanation_amount: int,
        model: str = "claude-3-opus-20240229",
        max_tokens: int = 1000,
        temperature: float = 0,
    ) -> dict[str, Any]:

        system_prompt = (
            f"You are an expert explanation generator. Generate {explanation_amount} explanations based on the given instructions. "
            "Provide the output solely in the specified JSON format, without any extra text or deviations."
        )
        assistant_prompt = (
            "Output the explanations strictly in the following JSON format:\n"
            '{"explanations": ["explanation1", "explanation2", ..., "explanation'
            + str(explanation_amount)
            + '"]}\n'
            "Do not include any additional text, commentary, or formatting outside the JSON structure."
        )

        message = client.messages.create(
            model=model,
            max_tokens=max_tokens,
            temperature=temperature,
            system=system_prompt,
            messages=[
                {"role": "user", "content": [{"type": "text", "text": text}]},
                {
                    "role": "assistant",
                    "content": [{"type": "text", "text": assistant_prompt}],
                },
            ],
        )
        questions = self._treat_response(message)
        return {"answer": questions}


if __name__ == "__main__":
    ig = InputGenerator()
    p = 5
    prompt, _ = explanation_prompt(p)
    response = ig.prompt_explanation_claude(ig.client, prompt, p)
    breakpoint()
    exit()
    prompt_questions = explanation_prompt(t=3, exp=p)
    questions: list[str] = cast(
        list[str], ig.prompt_question_gpt(prompt_questions, p)["Answer"][0]["questions"]
    )
    question_amount = len(questions)
    prompt_answers = answer_prompt(questions)
    answers = ig.prompt_answer_gpt(question_amount, prompt_answers)["Answer"][0][
        "answers"
    ]
    breakpoint()
    # question_list = [
    #     "What is RDF (Resource Description Framework) used for in the context of web development?",
    #     "Can you explain the basic structure of an RDF statement?",
    #     "How are ontologies used in the field of artificial intelligence?",
    #     "What is the role of genetic algorithms in the field of evolutionary computation?",
    #     "How do RDF triples differ from traditional data models?",
    #     "Why is it important to define ontologies when building intelligent systems?",
    #     "In genetic algorithms, what is the purpose of the crossover operation?",
    #     "How does RDF support interoperability on the web?",
    #     "What are some popular ontology languages used for developing ontologies?",
    #     "What are the key components of a genetic algorithm?",
    #     "How do you represent knowledge in RDF?",
    #     "What are some challenges associated with designing and maintaining ontologies?",
    #     "Why are genetic algorithms well-suited for optimization problems?",
    #     "How can ontologies be leveraged for semantic web applications?",
    #     "What role does mutation play in the genetic algorithm process?",
    #     "How does RDF support data integration across different systems?",
    #     "What are some real-world applications of genetic algorithms?",
    #     "How can ontologies facilitate natural language processing tasks?",
    #     "In what ways can genetic algorithms be personalized or customized for specific problem domains?",
    #     "What are some common tools and frameworks used for working with RDF data?",
    # ]
